name: family-ui CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build | cp ./CNAME ./build/CNAME
    - run: npm test
    - name: GitHub Pages Deploy
      uses: peaceiris/actions-gh-pages@v3.2.0
      deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      publish_dir: ./build
      allow_empty_commit: true
      publish_branch: gh-pages # deploying branch
  
      env:
        CI: true
